### Python Datascience 

This week we are going to use jupyter lab and jupyter notebooks to run our code 

- previously we used 
    - `spyder` on our local machines
    - `atom` on our local machines to remotely edit files on the server (though the `ftp-remote-edit package`) and run them through the terminal in atom that we connected to the cgat cluster using `ssh`
    
This week we are using `jupyter lab` and `jupyter notebooks` because we are doing some 'data science'.
This invloves looking at your files more and plotting things and its handy to be able to look at your output in the same document that your have your code. 

Jupyter notebooks allow you to:
- write text in 'markdown' format to annotate your code
- interactively write code and see what it outputs 
- display the output right where you've run it
- run command line statements 



All of the above, allow you to create a 'lab book' style document or report.


`.ipynb` files that can be easily converted to:
- a nice `.html` document or report thats easy to share and impress your colleagues
- a python script - sometimes handy if your trying out code but ultimately want a `.py` file to run 
- to do this you can click on `File/Export Notebook As` then choose `executable script` for `.py` file or `html` or `pdf` etc. 
    

### To run code in cells 

`Crl` + `Enter`

### Add Cells to run code in 
Click the '+' button above

### Good practise for Notebooks 

- At top of notebook run: 
    - date
    - the directory its running in 
    - your conda env 
    
We can use bash to get all of these - using the jupyter notebook and ipython magic `!`

In [1]:
!date
!pwd
! conda env list | grep '*'

Mon Feb  8 11:17:23 GMT 2021
/ifs/obds-training/jan21/aneesha/python_datascience
obds_py3              *  /ifs/obds-training/jan21/aneesha/conda/obds_conda/envs/obds_py3


### Numpy 

- Mathematical library 
- Fast mathmatical opertations on numeric datatypes 
- Allows N-dimensional tables - all must be same type (int64, float64 etc)
- Matrix Algebra
- Data structure = 'Arrays' (fast access to numeric data)

In [2]:

# import numpy library -> enable mathematical operations and create mutidimensional arrays
import numpy as np 

# create 2D matrix using np.array()  
x = np.array([[1,2,3],
              [4,5,6]], dtype=np.float64)
print('x')
print(x)


y = np.array([[7,8,9],
              [10,11,12]], dtype=np.float64)
print('y')
print(y)

x
[[1. 2. 3.]
 [4. 5. 6.]]
y
[[ 7.  8.  9.]
 [10. 11. 12.]]


#### Can do matrix algebra

In [ ]:
# sum the elements of 2 matrices together
print('Output from x+y :')
print(x + y)
print()  # this just outputs an empty line to make the output look cleaner

print('Can also use np.add(x,y) function:')
print(np.add(x,y))

#### Transpose (swap) rows and columns

In [ ]:
# origional x
print('Origional x')
print(x)

print()

# transpose x using .T
print("Transposed x")
print(x.T)

#### Numpy slicing of arrays 

- arrayname[rows, columns] 
- remember python is 0 based (start at 0)
- start_positon : end_possition + 1  -> get first 4 elements -> [0:5]

In [ ]:
z = [1,2,3,4,5,6,7,8,9]
z[0:4]

In [ ]:
# slicing array_name[cols, rows] ????????

# origional x
print('Origional x')
print(x)

print()

print ('x[:2] = rows from start to 2nd possition (row 0&1)')
print(x[:2])

print() 

print ('x[:, 1:3] = all rows, cols from start to 3rd possition (col 1-3)')
print(x[:,1:3])

print() 

print ('x[:2,1:3] = row 0 & 1 & col 1 - 2')
b = x[:2,1:3]
b

## Pandas = dataframes in python 

- built on numpy arrays
- adds rows and column metadata & labels 

#### Dataframes 

- one datatype per column (e.g. str, int, float, list etc.)
- Can be created from any 2D python data structure
    - Dictionary of lists
    - Dictionary of tuples 
    - Dictionary of series
    - Dictionary of Dictionaries 
    - List of dictionaries

### Pandas Series

- 1D vector built on NumPy array
- Includes label vector - can index on this
- Slice like a list [start_possition : stop_possition +1]
- Can have a series of any python object (e.g. str, int, float, boolean, dict, list etc)
- Must be all the same object type

In [5]:
# import numpy
import numpy as np
# import pandas
import pandas as pd

#### Create series with index or without

In [ ]:
# pandas creates default integer index​
s = pd.Series(['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight'])
s

In [ ]:
# pandas creates default integer index
# np.random.randn(5) = make array with 5 random numbers
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
s

#### Print attribute of series (e.g. index or name)

In [ ]:
# index & name are attributes of Series class​
print(s.index)
print(s.name)  # no name currently

### Slicing series

In [ ]:
# Slicing

print('Origional s:')
print(s, '\n') # print s then an empty line

print('s[:3] -> positions 0,1,2')

s[:3]        # list like slicing - pos 0-2

print(s[:3], '\n')

s['a']       # Index using labels

print("s['a'] -> value for pos 'a'")
print(s['a'], '\n')

s[[4, 3, 1]] # array-based indexing 

print('s[[4,3,1]] -> pos 4, 3, 2')
print(s[[4, 3, 1]], '\n')


#### Element wide computation

In [ ]:
s = pd.Series([1,2,3,4,5,6,7,8,9,10])

print('origional S')
print(s)
print()

s + s # element-wise addition
print('s + s')
print(s+s)
print()

s * 2 # element-wise multiplication
print('s * 2')
print(s*2)
print()

#### Create Dataframes

From a dictionary of series (could also be a dict of lists etc)

In [6]:


# dictionary - col names are dict 'keys', values are all in a 'list'
dict_of_genes = {'genes': ['Actb','Per1', 'Gapdh', 'Gata1','Eno1'], 
                 'counts': [550, 45, 984, 600, 123],
                 'control': [True, False, True, False, False]}

# use df as short for dataframe

df = pd.DataFrame(dict_of_genes)
df

genes  counts  control
0   Actb     550     True
1   Per1      45    False
2  Gapdh     984     True
3  Gata1     600    False
4   Eno1     123    False

In [ ]:
# Dataframe from dictionary of series
d = {'one': pd.Series([1., 2., 3.], 
                      index=['a', 'b', 'c']),
     'two': pd.Series([1., 2., 3., 4.],
                      index=['a', 'b', 'c', 'd'])}

print(d)

df = pd.DataFrame(d)
df

#### Read and write Dataframes from and to files 

#### Get Attributes of a Dataframe

In [ ]:
df.index   # row labels

In [ ]:
df.columns # column labels

In [ ]:
df.shape   # dataframe size

#### Viewing dataframes

df.head()

df.tail()

#### Get Summary of Dataframe information
 
df.info()

df.describe()

#### REad and write dataframe to file

```
# Read and write to CSV
df = pd.read_csv('file.csv')
df.to_csv('output.csv')

# tsv
df = pd.read_csv('file.tsv', sep='\t‘, header=0) df = pd.read_table(file_path) # tab default

# Excel
df = pd.read_excel('file.xlsx', 'Sheet1', index_col=None, na_values=['NA'])
df.to_excel('outfile.xlsx',sheet_name='Sheet1')

# HDF5
df = pd.read_hdf('file.h5', 'df')
df.to_hdf('foo.h5', 'df')
```

#### Add columns

In [ ]:
# Adding columns
df['three'] = df['one'] * df['two']
df['flag'] = df['one'] > 2

# Assign – (like dplyr mutate)
df = df.assign(four = df['one'] /df['two'])
df

#### Delete Columns

In [8]:
df.drop('four',axis=1) # need to save this to a variable to take effect, or use inplace=True in parameters

KeyError: "['four'] not found in axis"

In [ ]:
four = df.pop('four')
print(four)

#### Dataframe slicing, selecting and subsetting

In [ ]:
# Select single column
df['one']

In [ ]:
# Select multiple columns (list)
df[['two', 'one']] # any order

In [ ]:
# Slice data frame [rows]
df[:3]

In [ ]:
# get row by label -> returns series 
df.loc['b',:]

In [ ]:
# get row by label and then specific columns 
df.loc['c':, 'one':'three']


In [ ]:
# get row by interger location 
df.iloc[2:]
df.iloc[1:3, 2:3]

#### Boolean Indexing -> returns a dataframe

In [7]:
# select rows on column values
df[df.one > 1]    # can also do df[df['one'] > 1]

AttributeError: 'DataFrame' object has no attribute 'one'

In [ ]:
# select values on condition
df[df > 2]

### Exercise1

1) Read in a idxstats table you have generated for one of your samples on the course and save to variable called `idxdf`

2) Assign column names to table -> see http://www.htslib.org/doc/samtools-idxstats.html

3)Apply the `describe()` and `info()` methods to the `idxdf` object

4)Look at the `shape` and `index` attributes of `idxdf`

5) From `idxdf` select rows 6-12 and create a new variable called `idxdf2` 

6) From `idxdf` make a new dataframe `chr_mapped` consisting of columns 1&3 (chr & mapped). Save to a new file called `mapped_reads_per_chr.tsv` - make sure the output is tab seperated​


7) Create a new column for idxdf called `reads_per_base` by dividing number of `mapped reads` by `length` column

8) Subset the rows that have `reads_per_base` values greater than 0.05

9)Create a new column of length / 1 million to give a `length_Mbs` column (length in Megabases)

10) Subset the rows that have `reads_per_base` values greater than 0.05 and a chromosome length under 100 Mb

11) Delete the `reads_per_base` column

#### Sorting Dataframes 

```
# Sort by single column
df.sort_values(by=['col1'])

# Sort by multiple columns
df.sort_values(by=['col1', 'col2'])

# Descending order
df.sort_values(by='col1', ascending=False)

# NAs first
df.sort_values(by='col1', ascending=False, na_position='first')
```

#### Operations 
```
# Element-wise mathematical operations
df * 5
df **3

# Boolean logic
df1 & df2

# Numpy functions
np.log(df)

# Statistical summary
df.describe()

# statistical functions
df.mean() # per column
df.mean(axis=1) # per row

# Matrix algebra
df.T # transpose of matrix 
df.dot(df) # matrix multiplication

```

#### Apply Functions along an axis

```
# apply to entire dataframe
df.apply(np.sqrt)

# apply to cols
df.apply(np.sum, axis=0)


# apply to rows
df.apply(np.sum, axis=1)


```

#### Missing Data

```
# drop rows with nan
df.dropna(how='any')

# Replace nan with specific value
df.fillna(value=5)

# Create Boolean mask
pd.isna(df)
```

#### Categorical Data

```
df["biotype"] = df["raw_biotype"].astype("category")
df["biotype"].cat.categories = "protein_coding", "rRNA", "lincRNA"]


# Show distinct categories are present in dataset
df["biotype"].unique()

# Number of distinct categories 
df["biotype"].nunique()
```

#### Grouping

```
df.groupby('A').sum()

df.groupby(['A','C']).count().reset

```


#### String manipulation

In [ ]:
sample_names = {'samples' : ['mm_Chd7WTatac_R1','mm_Chd7WTatac_R2','mm_Chd7WTatac_R3','mm_Chd7KOatac_R1','mm_Chd7KOatac_R2','mm_Chd7KOatac_R3'],
                'file_type' : ['fastq.gz','fastq.gz','fastq.gz','fastq.gz','fastq.gz','fastq.gz']}
df = pd.DataFrame(sample_names)
df

In [ ]:
df['samples'].str.split('_')

In [ ]:
df['samples'].str.split('_',expand=True)

In [ ]:
df['replicate'] = df['samples'].str.split('_').str[-1]
df

#### Add column and set a value depending on another column

In [ ]:
df['samples'].str.contains('WT')

In [ ]:
df['condition'] = np.where(df['samples'].str.contains('WT'), 'WT', 'KO')
df

#### Combining Datasets


See documentation here: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

```
# Concatenate rows
pd.concat([df[:3], df[3:7], df[7:]])​

# Merge (inner by default)
result = pd.merge(df1, df2, on='key')
result = pd.merge(df1, df2, on='key', how='left')

# Join on index
result = df1.join(df2, how='outer')

# Join on key
result = df1.join(df2, on='key')
```

### Exercise 2

1) read in ensembl gtf files to create `gtf`

2) Assign appropriate column names https://www.ensembl.org/info/website/upload/gff.html

3) Find the unique values for 'source' column

4) Subset all values from 'ensembl_havana' and assign to new df called 'ens_df'

5) What is the size of ens_df?

6) What is the size of ens_df?

7) Group ens_df by 'feature' column & apply the 'count' function to get the number of rows in each feature

8) Create a new df called 'genes' by subsetting all rows with 'gene' as a feature

9) Create a new column called 'gene_length' and calculate the length of each gene

10) Calculate the mean and median of gene lengths

11) Find the top 10 longest genes

12) Find the lowest 20 shortest genes

13) Split attributes column on ';' and create new dataframe, merge this onto the ens_gtf dataframe using pandas merge ​

Extra: 
    Count the number of genes per chromosome, and add the number of genes per chomosome onto the idxdf from earlier ​